import { ogImage, OG_SIZE, OG_CONTENT_TYPE, OG_ALT } from '@/lib/og';

/* Added 30 August 2026, and the reason is a regression worth recording.
 *
 * This route had a share card without owning one: it declared no `openGraph`
 * object, so it inherited the root one from layout.tsx, and with it the image
 * generated by app/opengraph-image.tsx. Giving the page its own openGraph -
 * which it needed, because the inherited object also carried the HOMEPAGE's
 * og:url - replaced the whole object and took the image with it.
 *
 * That is the same Next behaviour that caused the problem being fixed:
 * openGraph is replaced, never merged. Caught by the quality sweep on the
 * build after the change, which is the argument for running the gates after
 * every edit rather than at the end of a session.
 */
export const runtime = 'edge';
export const size = OG_SIZE;
export const contentType = OG_CONTENT_TYPE;
export const alt = OG_ALT;

export default function Image() {
  return ogImage({
    eyebrow: 'Message sent',
    title: 'Thank you - your message has arrived.',
  });
}
