/* GENERATED by scripts/page-dates.mjs — do not edit by hand.
 *
 * Real last-commit dates for pages that have no `updated` field of their own.
 * The sitemap used the build timestamp for these, which made 45 URLs claim to
 * change on every deploy and taught Google to distrust lastmod site-wide.
 *
 * Regenerate after editing page content:  npm run dates
 *
 * A route absent from this map gets NO <lastmod> in the sitemap. Omitting the
 * field is a valid sitemap and an honest one; inventing a date is neither.
 */

export const PAGE_DATES: Record<string, string> = {
  "": "2026-08-09",
  "/about": "2026-08-09",
  "/services": "2026-08-09",
  "/approaches": "2026-08-09",
  "/pricing": "2026-08-14",
  "/contact": "2026-08-14",
  "/faq": "2026-08-14",
  "/online-counselling": "2026-08-09",
  "/guides": "2026-08-09",
  "/compare": "2026-08-09",
  "/for": "2026-08-09",
  "/resources": "2026-08-09",
  "/glossary": "2026-08-08",
  "/book": "2026-08-14",
  "/tools": "2026-08-09",
  "/reviews": "2026-08-09",
  "/punjabi": "2026-08-09",
  "/answers": "2026-08-10",
  "/careers": "2026-08-09",
  "/standards": "2026-08-09",
  "/editorial-policy": "2026-08-09",
  "/privacy": "2026-08-09",
  "/accessibility": "2026-08-09"
};

/** Collections whose items share one source module and so one honest date. */
export const COLLECTION_DATES: Record<string, string> = {
  "services": "2026-08-09",
  "tools": "2026-08-09",
  "locations": "2026-08-14",
  "punjabiRegions": "2026-08-14"
};

/** ISO-8601 for the sitemap, or null when we do not honestly know. */
export function lastmodFor(route: string): string | null {
  const d = PAGE_DATES[route];
  return d ? new Date(d + 'T00:00:00Z').toISOString() : null;
}

export function collectionLastmod(name: string): string | null {
  const d = COLLECTION_DATES[name];
  return d ? new Date(d + 'T00:00:00Z').toISOString() : null;
}
