#!/usr/bin/env node
/* Regenerates lib/page-dates.ts from real git history.
 *
 * WHY THIS EXISTS
 *
 * The sitemap used `new Date()` for every page without its own `updated` field
 * — the whole core set, tools, services, city and Punjabi region pages. That is
 * the build timestamp, so 45 of 113 URLs claimed to have changed at every
 * deployment whether or not a word of them had.
 *
 * That is worse than useless. Google evaluates, per site, whether a `lastmod`
 * can be believed, and a site whose dates all move on an unrelated deploy
 * teaches it to disregard the field entirely — taking the 66 URLs with genuine
 * dates down with it. The one crawl-priority signal a site controls directly,
 * spent on noise.
 *
 * WHY GENERATED RATHER THAN HAND-MAINTAINED
 *
 * A hand-kept map of "when did this page last really change" is wrong within a
 * month and nobody notices, because nothing fails. Git already knows the
 * answer, exactly, for free. This reads it and writes a checked-in file, so the
 * build itself needs no git (Vercel does not ship .git) and the data is still
 * real rather than asserted.
 *
 * Run after changing page content:  npm run dates
 * It is also worth running before a release; the check below prints a diff hint
 * rather than failing, because a stale date is a small problem and a broken
 * build over one is a bigger one.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, existsSync } from 'node:fs';

/* route path -> the file whose history actually determines that page's content.
 *
 * For collection pages the source of truth is the lib module holding the copy,
 * not the route component: editing a guide's text changes lib/guides-more3.ts
 * and never touches app/guides/[slug]/page.tsx. Those collections carry their
 * own `updated` field and are not listed here at all. */
const PAGES = {
  '': 'app/page.tsx',
  '/about': 'app/about/page.tsx',
  '/services': 'app/services/page.tsx',
  '/approaches': 'app/approaches/page.tsx',
  '/pricing': 'app/pricing/page.tsx',
  '/contact': 'app/contact/page.tsx',
  '/faq': 'lib/faq.ts',
  '/online-counselling': 'app/online-counselling/page.tsx',
  '/guides': 'app/guides/page.tsx',
  '/compare': 'app/compare/page.tsx',
  '/for': 'app/for/page.tsx',
  '/resources': 'app/resources/page.tsx',
  '/glossary': 'lib/glossary.ts',
  '/book': 'app/book/page.tsx',
  '/tools': 'app/tools/page.tsx',
  '/reviews': 'lib/reviews.ts',
  '/refer': 'app/refer/page.tsx',
  '/refer/doctor': 'app/refer/doctor/page.tsx',
  '/punjabi': 'app/punjabi/page.tsx',
  '/answers': 'app/answers/page.tsx',
  '/standards': 'lib/policies.ts',
  '/editorial-policy': 'lib/policies.ts',
  '/privacy': 'lib/policies.ts',
  '/accessibility': 'lib/policies.ts',
};

/* Collections without their own `updated` field. Their pages are generated from
 * one module, so that module's history is the honest date for all of them. */
const COLLECTIONS = {
  services: 'lib/services.ts',
  tools: 'lib/tools.ts',
  locations: 'lib/locations.ts',
  punjabiRegions: 'lib/punjabi-regions.ts',
  /* ADDED 3 Sep 2026. These four cover 143 pages that had no date on any
     surface: no <lastmod> in the sitemap and no dateModified in their
     structured data. They are the pages an answer engine would cite for
     "counselling in Surrey" or for either counsellor by name, so they were
     precisely the wrong ones to leave undated. All four existed as modules
     before this; nobody had added them to the map. */
  cityServices: 'lib/city-services.ts',
  practitioners: 'lib/practitioners.ts',
  practitionerPlaces: 'lib/practitioner-places.ts',
  tagalog: 'lib/tagalog-guides.ts',
  tagalogPlaces: 'lib/practitioner-places-tl.ts',
  tagalogLanding: 'lib/tagalog-landing.ts',
  conditions: 'lib/conditions.ts',
  glossary: 'lib/glossary.ts',
  faq: 'lib/faq.ts',
};

const lastCommit = (file) => {
  if (!existsSync(file)) return null;
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
      encoding: 'utf8',
    }).trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : null;
  } catch {
    return null;
  }
};

const pages = {};
const missing = [];
for (const [route, file] of Object.entries(PAGES)) {
  const d = lastCommit(file);
  if (d) pages[route] = d;
  else missing.push(`${route} (${file})`);
}

const collections = {};
for (const [name, file] of Object.entries(COLLECTIONS)) {
  const d = lastCommit(file);
  if (d) collections[name] = d;
  else missing.push(`${name} (${file})`);
}

const banner = `/* GENERATED by scripts/page-dates.mjs — do not edit by hand.
 *
 * Real last-commit dates for pages that have no \`updated\` field of their own.
 * The sitemap used the build timestamp for these, which made 45 URLs claim to
 * change on every deploy and taught Google to distrust lastmod site-wide.
 *
 * Regenerate after editing page content:  npm run dates
 *
 * A route absent from this map gets NO <lastmod> in the sitemap. Omitting the
 * field is a valid sitemap and an honest one; inventing a date is neither.
 */`;

const body = `${banner}

export const PAGE_DATES: Record<string, string> = ${JSON.stringify(pages, null, 2)};

/** Collections whose items share one source module and so one honest date. */
export const COLLECTION_DATES: Record<string, string> = ${JSON.stringify(collections, null, 2)};

/** ISO-8601 for the sitemap, or null when we do not honestly know. */
export function lastmodFor(route: string): string | null {
  const d = PAGE_DATES[route];
  return d ? new Date(d + 'T00:00:00Z').toISOString() : null;
}

export function collectionLastmod(name: string): string | null {
  const d = COLLECTION_DATES[name];
  return d ? new Date(d + 'T00:00:00Z').toISOString() : null;
}
`;

writeFileSync('lib/page-dates.ts', body);

console.log(`  lib/page-dates.ts written — ${Object.keys(pages).length} pages, ${Object.keys(collections).length} collections`);
if (missing.length) {
  console.log(`  no git history for ${missing.length} (these will emit no <lastmod>, which is correct):`);
  for (const m of missing) console.log(`    ${m}`);
}
